- name: Enable the firewall
  become: yes
  community.general.ufw:
    state: enabled
    policy: deny
  when: enableFirewall | bool

- name: Set logging
  become: yes
  community.general.ufw:
    logging: 'on'
  when: setLogging | bool

- name: Connection rate limiting
  become: yes
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  when: rateLimiting | bool

- name: Allow SSH
  become: yes
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: allowSSH | bool

- name: Delete OpenSSH rule
  become: yes
  community.general.ufw:
    rule: allow
    name: OpenSSH
    delete: yes
  when: deleteSSH | bool

- name: Allow HTTP
  become: yes
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: allowHttp | bool

- name: Allow HTTPS
  become: yes
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
  when: allowHttps | bool

- name: Deny all access to port 53
  become: yes
  community.general.ufw:
    rule: deny
    port: '53'
  when: port53 | bool