---
# 
# Playbook for the Supermicro-1 Machine
#

- hosts: supermicro-1
  name: Apply networking configuration
  roles:
    - netplan 

- hosts: supermicro-1
  name: Apply disk layout to R620 hosts and setup LXD
  roles:
    - lvm-r620
    - lxd
