---
# 2021 owner: Lili
# Playbook for the Supermicro-2 Machine
#
# This machine is deployed by MAAS and hosts jupyter
#

### FIXME: Software RAID is assembled by hand. 
# /dev/md1: 600GB RAID1 - SSD
# /dev/md2: 1.2TB RAID1 - SSD (called disk)
#
- hosts: supermicro-2
  name: Apply networking configuration
  remote_user: ubuntu
  roles:
    - netplan 

- hosts: supermicro-2
  name: Apply disk layout and install LXD
  remote_user: ubuntu
  roles:
    - lvm
    - lxd
#
#- hosts: dell-r630-1
#  name: Setup dell-r630-1 to serve jupyter hub.
#  tags:
#    - jupyter
#  roles:
#    - jupyter
